name: Build JAR

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3 #https://github.com/actions/checkout/releases
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0 #https://github.com/actions/setup-java/releases
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon
      - uses: actions/upload-artifact@v3.1.2 #https://github.com/actions/upload-artifact/releases
        with:
          name: Iris
          path: build/libs/Iris-*.jar
